const contractAddress = "0x699D43B2f9C388C53c44E8f56De5c05Fb3a4b74c"; // Replace with your own contract address
const chain = 'goerli'; // goerli, polygon, or ethereum

const welcome_h1 = "Welcome to SUPREMECULT";
const welcome_h2 = "Connect to MetaMask to Get Started";
const welcome_p = 'A power house of/in Pluto .. One of the strongest Sects/Religions in Pluto as we believe, represented by 14 Majors.';
const h1_presale_coming_soon = "NFT Drop on it's way!!";
const h1_presale_mint = "Pre-Sale Mint Open!!";
const h1_public_mint = "Public Mint Open!!";
const h2_presale_coming_soon = "Pre-Sale Mint Countdown";
const h2_presale_mint = "Public Mint Countdown";
const p_presale_coming_soon = "We are working hard to launch the NFT Collection. Stay tuned for updates!";
const p_presale_mint_not_whitelisted = "You are not whitelisted for the pre-sale.. 😢";
const p_presale_mint_whitelisted = "You're on the whitelist for the pre-sale! 🎉";
const p_presale_mint_already_minted = "You've already claimed your whitelist mint. Thank you! 🎉";
const p_public_mint = "No whitelist needed. Public minting is now open! 🎉";
const button_presale_coming_soon = "Get on the Whitelist";
const button_presale_mint_whitelisted = "Mint Your Unigue piece of NFT";
const button_presale_mint_not_whitelisted = "Get on the Whitelist";
const button_presale_already_minted = "Join The Community";
const button_public_mint = "Mint Your NFT";
const mint_failed = "Minting failed. 😢 Please try again.";
